//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVTrade.Areas.Personal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowedProduct
    {
        public int showedProductID { get; set; }
        public int productID { get; set; }
        public int userID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
