//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVTrade.Areas.Personal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.User = new HashSet<User>();
        }
    
        public int userGroupID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
