//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int articleID { get; set; }
        [DisplayName("Заголовок")]
        public string title { get; set; }
        public int userID { get; set; }
        public string imageURL { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual User User { get; set; }
    }
}
