//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoosedCategory
    {
        [HiddenInput(DisplayValue = false)]
        public int chosenCategoryID { get; set; }

        [DisplayName("Категорія товару")]
        [Required(ErrorMessage = "Оберіть категорію")]
        public int productCategoryID { get; set; }

        [DisplayName("Користувач")]
        [Required(ErrorMessage = "Оберіть користувача")]
        public int userID { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual User User { get; set; }
    }
}
