//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoosedCategory
    {
        public int chosenCategoryID { get; set; }
        public int productCategoryID { get; set; }
        public int userID { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual User User { get; set; }
    }
}
