//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public OrderStatus()
        {
            this.Order = new HashSet<Order>();
        }
    
        [HiddenInput(DisplayValue = false)]
        public int? statusID { get; set; }

        [DisplayName("Назва")]
        [Required(ErrorMessage = "Поле не може бути пустим")]
        public string name { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
