//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderID { get; set; }
        public System.DateTime orderDate { get; set; }
        public string finishDate { get; set; }
        public int productID { get; set; }
        public int userID { get; set; }
        public double amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
