//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ReservedProduct = new HashSet<ReservedProduct>();
        }
    
        [HiddenInput(DisplayValue = false)]
        
        public int orderID { get; set; }

        [DisplayName("Дата замовлення")]
        [DataType(DataType.Date)]
        public System.DateTime orderDate { get; set; }

        [DisplayName("Дата доставки")]
        [DataType(DataType.Date)]
        public System.DateTime finishDate { get; set; }

        [DisplayName("Товар")]
        [Required(ErrorMessage = "Оберіть товар")]
        public int productID { get; set; }

        [DisplayName("Користувач")]
        [Required(ErrorMessage = "Оберіть користувача")]
        public int userID { get; set; }

        [DisplayName("Кількість(кг)")]
        [Required(ErrorMessage = "Поле не може бути пустим")]
        public double amount { get; set; }

        [DisplayName("Дата останньої зміни статусу")]
        [DataType(DataType.Date)]
        public System.DateTime statusDate { get; set; }

        [DisplayName("Статус")]
        [Required(ErrorMessage = "Оберіть статус")]
        public int statusID { get; set; }

        [DisplayName("Виконано")]
        public bool completed { get; set; }

        [DisplayName("Відхилено")]
        public bool canceled { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ReservedProduct> ReservedProduct { get; set; }
    }
}
