//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            this.ChoosedCategory = new HashSet<ChoosedCategory>();
            this.Product = new HashSet<Product>();
            this.ProductToBuy = new HashSet<ProductToBuy>();
        }
    
        public int productCategoryID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<ChoosedCategory> ChoosedCategory { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<ProductToBuy> ProductToBuy { get; set; }
    }
}
