//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedProduct
    {
        [HiddenInput(DisplayValue = false)]
        public int reservID { get; set; }

        [DisplayName("Замовлення")]
        [Required(ErrorMessage = "Оберіть замовлення")]
        public int orderID { get; set; }

        [DisplayName("Товар")]
        [Required(ErrorMessage = "Оберіть товар")]
        public int productID { get; set; }

        [DisplayName("Користувач")]
        [Required(ErrorMessage = "Оберіть користувача")]
        public int userID { get; set; }

        [DisplayName("Кількість(кг)")]
        [Required(ErrorMessage = "Поле не може бути пустим")]
        public double amountOfProduct { get; set; }

        [DisplayName("Дата")]
        [Required(ErrorMessage = "Поле не може бути пустим")]
        [DataType(DataType.DateTime)]
        public System.DateTime date { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
