//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class User
    {
        public User()
        {
            this.Article = new HashSet<Article>();
            this.ChoosedCategory = new HashSet<ChoosedCategory>();
            this.Order = new HashSet<Order>();
            this.Product = new HashSet<Product>();
            this.ShowedProduct = new HashSet<ShowedProduct>();
        }
    
        public int userID { get; set; }

        [Required(ErrorMessage = "Ведіть пароль", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Пароль має бути більше 8 символів")]
        public string password { get; set; }
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [System.Web.Mvc.CompareAttribute("password")]
        public string ConfirmPassword { get; set; }
        public int userGroupID { get; set; }

        [Required(ErrorMessage = "Введіть назву компанії", AllowEmptyStrings = false)]
        public string companyName { get; set; }

        [Required(ErrorMessage = "Введіть юридичну адресу", AllowEmptyStrings = false)]
        public string juridicalAddress { get; set; }

         [Required(ErrorMessage = "Введіть адресу потужностей", AllowEmptyStrings = false)]
        public string address { get; set; }

         [Required(ErrorMessage = "Введіть контактну особу", AllowEmptyStrings = false)]
        public string contactPerson { get; set; }

         [Required(ErrorMessage = "Введіть посаду", AllowEmptyStrings = false)]
        public string post { get; set; }

         [Required(ErrorMessage = "Введіть номер телефону", AllowEmptyStrings = false)]
        public string phoneNumber { get; set; }

        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",
                    ErrorMessage = "Please provide valid email id")]
         
        public string email { get; set; }
        public bool merchantLicense { get; set; }
        public bool tradeLicense { get; set; }
    
        public virtual ICollection<Article> Article { get; set; }
        public virtual ICollection<ChoosedCategory> ChoosedCategory { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<ShowedProduct> ShowedProduct { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
