//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int articleID { get; set; }
        public string title { get; set; }
        public int userID { get; set; }
        public string imageURL { get; set; }
        public string description { get; set; }
        public System.DateTime expirationDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
