//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderID { get; set; }
        public System.DateTime orderDate { get; set; }
        public System.DateTime finishDate { get; set; }
        public int productID { get; set; }
        public int userID { get; set; }
        public double amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
