//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Order = new HashSet<Order>();
            this.ShowedProduct = new HashSet<ShowedProduct>();
        }
    
        public int productID { get; set; }
        public string name { get; set; }
        public int productCategoryID { get; set; }
        public string imageURL { get; set; }
        public double amount { get; set; }
        public double price { get; set; }
        public string description { get; set; }
        public int userID { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ShowedProduct> ShowedProduct { get; set; }
    }
}
