//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Article = new HashSet<Article>();
            this.ChoosedCategory = new HashSet<ChoosedCategory>();
            this.Order = new HashSet<Order>();
            this.Product = new HashSet<Product>();
            this.ShowedProduct = new HashSet<ShowedProduct>();
        }
    
        public int userID { get; set; }
        public string password { get; set; }
        public int userGroupID { get; set; }
        public string companyName { get; set; }
        public string juridicalAddress { get; set; }
        public string address { get; set; }
        public string contactPerson { get; set; }
        public string post { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public bool merchantLicense { get; set; }
        public bool tradeLicense { get; set; }
        public string passwordSalt { get; set; }
    
        public virtual ICollection<Article> Article { get; set; }
        public virtual ICollection<ChoosedCategory> ChoosedCategory { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<ShowedProduct> ShowedProduct { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
